services:
  - type: web
    name: mi-fastapi
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app.main:app --host 0.0.0.0 --port $PORT